---
title: Fyrirlestur 1.3 — Ósamstillt forritun
---

# Fyrirlestur 1.3 — Ósamstillt forritun

## Vefforritun 2 — HBV403G

### Ólafur Sverrir Kjartansson, [osk@hi.is](mailto:osk@hi.is)

---

## Ósamstillt forritun (async programming)

* Þegar forrit nýta hluti sem eru ekki í minni þurfum við að beita öðrum aðferðum í forritun
* Það er _hratt_ að sækja hluti í minni, _hægara_ að sækja á disk og enn _hægara_ að sækja yfir net
* Bíðum ekki eftir því að beiðni klárist, nýtum _ósamstillta forritun_ (asynchronous/async programming)

***

![Dæmi um mismunandi forritun](img/control-io.svg "Mynd frá https://eloquentjavascript.net/11_async.html")

***

## Promises

* Hjúpun fyrir gildi sem mun verða til í framtíðinni
* Gerir asynchronous forritun auðveldari
* Flóknara hugtak en callbacks

***

* Þegar við skilgreinum Promise köllum við í:
  - `resolve` með gildi þegar við höfum lokið aðgerð
  - `reject` með villu þegar eitthvað fer úrskeiðis

***

* Þegar við vinnum með promise skilgreinum við
  - `then` callback til að vinna með gildið, fær gildi sem argument
  - `catch` callback til að vinna með villu, fær villu sem argument
* `then` og `catch` eru föll á Promise
* Getum sent promise gildi á milli!

***

```javascript
function futureMessage(msg) {
  return new Promise((resolve, reject) => {
    if (msg === 'foo') reject(new Error('nope'));

    setTimeout(
      () => resolve(`${msg} from future!`),
      2000,
    );
  });
}
futureMessage('Hi!').then(s => console.log(s));
// "Hi! from future!" eftir 2 sek
futureMessage('foo').catch(s => console.log(s));
// "nope" strax
```

***

## Promise.all

* `Promise.all` tekur við fylki af Promise og skilar Promise
  - Ef eitthvert rejactarar er Promise rejectað
  - Niðurstaða er fylki með niðurstöðu í réttri röð m.v. uppruna

***

## Promise.race

* `Promise.race` tekur við fylki af Promise og skilar Promise
  - Skilar niðurstöðu úr fyrsta Promise sem lýkur eða rejectar

***

## Stöður á promise

Promise getur verið í einni af þrem stöðum:

* `pending`, verið að bíða eftir gildi
* `fulfilled`, búið að uppfylla loforð með gildi
* `rejected`, búið að hafna loforði með villu

***

## Promises & Node.js

* Node.js hefur stuðning við promises sem gerir það auðveldara að vinna með async kóða
* Frá og með útgáfu 8 getum við notað `util.promisify` til að breyta callback API í promise API

***

## util.promisify

```javascript
const util = require('util');
const fs = require('fs');

const readFileAsync = util.promisify(fs.readFile);

readFileAsync('data.txt')
  .then((data) => {
    console.log(data.toString('utf8'));
  })
  .catch((err) => {
    console.error(err);
  });
```

***

## async og await

* Frá og með útgáfu 7.6 hefur Node.js stutt `async` og `await`
* Enn önnur leið til að vinna með async kóða, kemur frá C#
* Notum `await` til að bíða eftir promises
* Verðum að merkja föll sem nota `await` með `async`

***

* Kóðinn okkar verður töluvert grynnri og læsilegri
* Notum `try catch` fyrir villumeðhöndlun
* `async` fallið skilar Promise!
  - `async await` er _syntactic sugar_ fyrir Promise
  - Ættum að hafa `catch` á það fall til að vera örugg um að missa ekki af villum

***

```javascript
const util = require('util');
const fs = require('fs');

const readFileAsync = util.promisify(fs.readFile);
async function main() {
  let data = '';
  try {
    data = await readFileAsync('data.txt');
  } catch (e) {
    console.error('error', e);
  }
  console.log(data.toString('utf8'));
}
main().catch((err) => { console.error(err); });
```

***

## Villur sem ekki eru gripnar

* Ef við skrifum forrit sem nota promises og `async await` er líklegt að villa verði ekki meðhöndluð á einhverjum tímapunkti
* Fáum `UnhandledPromiseRejectionWarning` frá Node.js
  - Í framtíðinni mun það stöðva keyrslu á forriti

***

## `unhandledRejection`

* Node.js skilar frá sér `unhandledRejection` atburð þegar þetta á sér stað
* Getum gripið með `process.on('unhandledRejection', (reason, p) => { /* ... */ })`
* Ættum aðeins að nota til að logga og debugga, [forritið okkar verður komið í óskilgreinda stöðu](https://nodejs.org/api/process.html#process_warning_using_uncaughtexception_correctly)
